spring:
  application:
    name: hrm-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: MySQL
#    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
server:
  port: 9002
jwt:
  config:
    ttl: 3600000
    key: colin

    #单个文件数据大小限制
#    spring.http.multipart.maxFileSize = 20Mb
#    #每次上传总数据大小限制
#    spring.http.multipart.maxRequestSize=100Mb

#  feign.hystrix.enabled=true
#  #熔断器失败的个数==进入熔断器的请求达到1000时服务降级（之后的请求直接进入熔断器）
#  hystrix.command.default.circuitBreaker.requestVolumeThreshold=1000
#  #回退最大线程数
#  hystrix.command.default.fallback.isolation.semaphore.maxConcurrentRequests=50
#  #核心线程池数量
#  hystrix.threadpool.default.coreSize=130
#  #请求处理的超时时间
#  hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=100000
#  ribbon.ReadTimeout=120000
#  #请求连接的超时时间
#  ribbon.ConnectTimeout=130000
feign:
  hystrix:
    enable: true
hystrix:
  threadpool:
    default:
      coreSize: 100

eureka:
  instance:
    #在eureka中显示ip地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/

