spring:
  application:
    name: hrm-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
server:
  port: 9002
jwt:
  config:
    ttl: 3600000
    key: colin

    #单个文件数据大小限制
#    spring.http.multipart.maxFileSize = 20Mb
#    #每次上传总数据大小限制
#    spring.http.multipart.maxRequestSize=100Mb
eureka:
  instance:
    #在eureka中显示ip地址
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/

